@url = http://localhost:8080/api/location


GET {{url}} HTTP/1.1

### Location 1
GET {{url}}/1 HTTP/1.1



###
POST {{url}} HTTP/1.1
Content-Type: application/json

{
  "address": "18 Washington Ave",
  "city": "Boston",
  "state": "MA",
  "zipCode": 20235
}


### 
PUT {{url}}/1 HTTP/1.1
Content-Type: application/json

{
  "address": "18 Washington Ave",
  "city": "Boston",
  "state": "MA",
  "zipCode": 20235
}


###
DELETE {{url}}/1 HTTP/1.1