@url = http://localhost:8080/api/vehicle


GET {{url}} HTTP/1.1

### Ford
GET {{url}}/id/1 HTTP/1.1

### Honda
GET {{url}}/id/2 HTTP/1.1

### Toyota
GET {{url}}/id/3 HTTP/1.1

### Get by zip code
GET {{url}}/zipcode/20235

###
POST {{url}} HTTP/1.1
Content-Type: application/json

{
    "make": "Test Make",
    "model": "Test Model",
    "year": 2023,
    "color": "Teal",
    "trim": "Oversize",
    "rentRate": 45.00,
    "leaseRate": 390.00,
    "dealershipId": 1,
    "bookingStatus": false
}

###
POST {{url}} HTTP/1.1
Content-Type: application/json

{
    "make": "Next Test",
    "model": "Test Delete Model",
    "year": 2020,
    "rentRate": 45.00,
    "leaseRate": 390.00,
    "dealershipId": 1
}

### 
PUT {{url}}/4 HTTP/1.1
Content-Type: application/json

{
    "vehicleId": 4,
    "make": "Test Make",
    "model": "Test Model",
    "year": 2023,
    "color": "Orange",
    "trim": "Sport",
    "rentRate": 45.00,
    "leaseRate": 390.00,
    "dealershipId": 1,
    "bookingStatus": true
}

### Test Make
GET {{url}}/id/4 HTTP/1.1

###
DELETE {{url}}/6 HTTP/1.1